### ISSUE TITLE
Universal translations

### ISSUE THREAD

**Issue by neov-98** [Junvary/gin-quasar-admin#10]
Hello.
I want to clarify the translations.
If the project positions support for many languages, then I suggest:
1. Write comments both in code and in GIT in English.
2. Make translations of phrases as a whole, not words separately. For example, the Russian language has many forms of endings and word translation, and then the sentence assembly will not be able to follow the context of the phrase output.

Code:
```
$q.dialog({
        title: t('Reset') + t('Password'),
        message: t('Confirm') + t('Reset') + t('Password') + '?' + '(' + row.username + ')',
        cancel: true,
        persistent: true,
    })
```

Replace with:
``` 
$q.dialog({
        title: t('Reset Password'),
        message: t('Confirm Reset Password?') + ' ' + '(' + row.username + ')',
        cancel: true,
        persistent: true,
    })
```

Translate Russian:
```
...
    "Reset": "Cброс",
    "Password": "Пароль",
    "Confirm": "Подтверждение",
...

...
    "Reset Password": "Cброс пароля",
    "Confirm Reset Password?": "Подтвердите сброс пароля?",
...
```
If there is no translation, a readable key in English is output

If you accept my offer, I am ready to help with the Russian translation.

**Comment by Junvary** [comment]
Good idea.Let's do it!

**Comment by neov-98** [comment]
OK, I'll do a PR with the addition of the Russian language.

Next, we will gradually replace the assemblies with whole phrases.

The second point is that it may be necessary to transfer the translations to a JSON file.
How do you see it?

**Comment by Junvary** [comment]
I will rebuild the JSON files soon.
