### ISSUE TITLE
Data migration after plugin creation

### ISSUE THREAD

**Issue by neov-98** [Junvary/gin-quasar-admin#12]
Is there an easier way to start migrations and database filling after creating a plugin?

At the moment, after creating the plugin, you need to delete the database and clear the config, then the system starts initialization and the data is filled in with the data of the new plugin.

**Comment by Junvary** [comment]
@Vadim-vg 
Createing plugin is not completed.
It's just an initial version.
And please complete the JSON file in https://github.com/Junvary/gin-quasar-admin/pull/11
Then i'll merge it.
