### ISSUE TITLE
数据库文件

### ISSUE THREAD

**Issue by kinbod** [Junvary/gin-quasar-admin#18]
怎么没有数据库文件呢？？？

**Comment by Junvary** [comment]
无需数据库文件，直接初始化。

**Comment by kinbod** [comment]
好的，已经好了，，，还停留在java之前的过程中。。。gin gorm的确厉害

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年9月15日 15:27
收件人: ***@***.***>
抄送: Bodkin ***@***.***>; ***@***.***>
主题: Re: [Junvary/gin-quasar-admin] 数据库文件 (Issue #18)


无需数据库文件，直接初始化。

―
