### ISSUE TITLE
I18N title error

### ISSUE THREAD

**Issue by orzMaster** [Junvary/gin-quasar-admin#3]
GQA-FRONTEND/src/i18n/en-US/index.js
line 99 ColseOther => CloseOther
GQA-FRONTEND/src/i18n/zh-CN/index.js
line 99 ColosOther => CloseOther

**Comment by Junvary** [comment]
> GQA-FRONTEND/src/i18n/en-US/index.js line 99 ColseOther => CloseOther GQA-FRONTEND/src/i18n/zh-CN/index.js line 99 ColosOther => CloseOther

Thanks,fix it in the next commit
